title: Patrick Cannon
description: ""
author:
  name: "Patrick Cannon"
  email: "tempemail@email.email.com"
  url: "https://cannonpatrick.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Patrick Cannon"
year : "2020"
